.. This (-*- rst -*-) format file contains commonly used link targets and name
   substitutions.  It may be included in many files, therefore it should only
   contain link targets and name substitutions. Try grepping for "^\.\. _" to
   find plausible candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for:
   nipy, NIPY, Nipy, etc...


.. project

.. _project pypi: https://pypi.org/project/stimuli/
.. _project conda: https://anaconda.org/conda-forge/stimuli
.. _project license: https://github.com/mscheltienne/stimuli/blob/main/LICENSE


.. license

.. _MIT license: https://opensource.org/licenses/MIT


.. softwares

.. _uv: https://github.com/astral-sh/uv
.. _portaudio: https://www.portaudio.com/
.. _psychopy: https://www.psychopy.org/
.. _scipy: https://scipy.org/
.. _sounddevice: https://python-sounddevice.readthedocs.io/en/latest/
