.. NOTE: we use cross-references to highlight new functions and classes.
   Please follow the examples below, so the whats_new page will have a link to
   the function/class documentation.

.. NOTE: there are 3 separate sections for changes, based on type:
   - "Enhancements" for new features
   - "Bugs" for bug fixes
   - "API changes" for backward-incompatible changes

.. NOTE: changes from first-time contributors should be added to the TOP of
   the relevant section (Enhancements / Bugs / API changes), and should look
   like this (where xxxx is the pull request number):

       - description of enhancement/bugfix/API change (:pr:`xx` by
       `Firstname Lastname`_)

   Also add a corresponding entry for yourself in doc/changes/names.inc

.. _current:

Version 0.5
-----------

Enhancements
~~~~~~~~~~~~

- ***

Bugs
~~~~

- ***

API and behavior changes
~~~~~~~~~~~~~~~~~~~~~~~~

- ***

Authors
~~~~~~~

* Mathieu Scheltienne
